# -*- coding: utf-8 -*-
"""API_by_The_Dog.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iPcfR-838ek3lRF2nMMTWT9Ueh-gy-3O
"""

## for loop โดยลองดึงข้อมูลสายพันธุ์สุนัขจาก The Dog API
import requests
import time # เพื่อให้มีการ Relay ของการดึงข้อมูล

# API Key
api_key = "live_kCPFT3hIPLP2ra0p1LfmRgQ0mCZdU60FyXIpokCeCkV82adNYIAVLMyoTZAp6BxO"

dog = [] # เตรียม dog ไว้ใส่ข้อมูล

for i in range(10): # limit data 10

    url = f"https://api.thedogapi.com/v1/breeds/{i+1}"
    headers = {"x-api-key": api_key}

    response = requests.get(url, headers=headers)
    response_json = response.json()

    item = response_json
    # ดึงข้อมูลที่ต้องการ
    data = [item.get("name"), item.get("temperament"), item.get("life_span")]

    dog.append(data)
    print(f"Success: {i+1} - {item.get('name')}")
    time.sleep(1) # สั่งให้ Relay 1 วินาที ก่อนจะหาหมาตัวต่อไป

print(dog)

# Pandas
import pandas as pd
dog_data = pd.DataFrame(dog,
columns = ["Breed Name", "Temperament", "Life Span"])
dog_data

