# -*- coding: utf-8 -*-
"""API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iPcfR-838ek3lRF2nMMTWT9Ueh-gy-3O
"""

# Install Package
import random

#--------- Logo --------

logo = r"""
                    /\/\,\,\ ,
                    /        ` \'\,
                  /               '/|_
                  /                   /
                /                   /
                /                   ;
                ;-''-.  ____       ,
              /      )'    `.     '
              (    o |        )   ;
              ),''''\    o   ;  :
              ;\___  `._____/ ,-:
              ;                 @ )
            /                `;-'
          ,. `-.______________,|
    ,(`._||         \__\__\__)|
    ,`.`-   \        '.        |
    `._  ) :          )______,;\_
        \    \_   _,--/       ,   `.
        \     `--\   :      /      `.
          \        \  ;     |         \
          `-._____ ;|      |       _,'
      -hrr-       \/'      `-.----' \
                    /          \      \
        """

end_logo = r"""
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  GAME OVER  @@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
"""

#--------- End Logo --------

# 1. Game data
emoji = ["👊", "✋", "✌️"]
player_name = input("Enter your name: ")
print(f"Welcome '🎉>'{player_name}'<🎉' to the game!\n")
print(logo)

while True:
    print(f"\n--- ({player_name}) ---")
    # Input type with text
    user_input = input("What do you choose? 0: 👊 rock, 1: ✋ paper, 2: ✌️ scissors (Type 'done' to Exit): ")

    # Exist done with "Done"
    if user_input.lower() == "done":
        print("------------------------------------------")
        print(f"Goodbye {player_name}! Thanks for playing.")
        print("------------------------------------------")
        print(end_logo)
        break
    player = int(user_input)

    # 2. Computer player
    comp = random.randint(0, 2)
    print(f"Your Choose: {emoji[player]} VS Comp Choose: {emoji[comp]}")

    # 3. Decide the result
    if player == comp:
        print("We are Draw!")
    elif (player == 0 and comp == 2) or (player == 1 and comp == 0) or (player == 2 and comp == 1):
        print("You Win! 🎉")
    else:
        print("You Lose! 🤖")

